# Generated by Django 2.2.14 on 2020-09-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('collage', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
    ]
