# Generated by Django 2.2.14 on 2020-09-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stud_record',
            table='stud_record',
        ),
    ]
